title: IOE2022 Tomas
iconURL: assets/default-icon.png
theme: jekyll-theme-leaf

# for a clean URL
permalink: :slug

social:
  twitter: toomas_ps
  github: Tresillo2017

plugins:
 - jekyll-feed
 - jekyll-seo-tag

### comments & analytics
hyvor_talk_website_id: 5800
google_analytics: UA-NNNNNNNN-N